Document: alternc-oneclickinstallers
Title: Debian alternc-oneclickinstallers Manual
Author: <insert document author here>
Abstract: This manual describes what alternc-oneclickinstallers is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/alternc-oneclickinstallers/alternc-oneclickinstallers.sgml.gz

Format: postscript
Files: /usr/share/doc/alternc-oneclickinstallers/alternc-oneclickinstallers.ps.gz

Format: text
Files: /usr/share/doc/alternc-oneclickinstallers/alternc-oneclickinstallers.text.gz

Format: HTML
Index: /usr/share/doc/alternc-oneclickinstallers/html/index.html
Files: /usr/share/doc/alternc-oneclickinstallers/html/*.html
